# Part 1: Exploring Tensors

In [15]:
import torch
import numpy as np
from torch import nn

# Task 1.1: Creating Tensors
print("=== Task 1.1: Creating Tensors ===")

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from list:\n{x_data}\n")

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy array:\n{x_np}\n")

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

print(f"Shape: {x_rand.shape}, dtype: {x_rand.dtype}, device: {x_rand.device}\n")

=== Task 1.1: Creating Tensors ===
Tensor from list:
tensor([[1, 2],
        [3, 4]])

Tensor from NumPy array:
tensor([[1, 2],
        [3, 4]])

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.9129, 0.2771],
        [0.8289, 0.3624]])

Shape: torch.Size([2, 2]), dtype: torch.float32, device: cpu



In [16]:
# Task 1.2: Tensor operations
print("=== Task 1.2: Tensor Operations ===")
print(f"x_data + x_data:\n{x_data + x_data}\n")
print(f"x_data * 5:\n{x_data * 5}\n")
print(f"x_data @ x_data.T:\n{x_data @ x_data.T}\n")

=== Task 1.2: Tensor Operations ===
x_data + x_data:
tensor([[2, 4],
        [6, 8]])

x_data * 5:
tensor([[ 5, 10],
        [15, 20]])

x_data @ x_data.T:
tensor([[ 5, 11],
        [11, 25]])



In [17]:
# Task 1.3: Indexing and Slicing
print("=== Task 1.3: Indexing and Slicing ===")
print(f"First row: {x_data[0]}")
print(f"Second column: {x_data[:, 1]}")
print(f"Element (1,1): {x_data[1,1]}\n")

=== Task 1.3: Indexing and Slicing ===
First row: tensor([1, 2])
Second column: tensor([2, 4])
Element (1,1): 4



In [18]:
# Task 1.4: Reshaping
print("=== Task 1.4: Reshape ===")
x = torch.rand(4,4)
print(f"Original shape: {x.shape}")
reshaped = x.view(16,1)
print(f"Reshaped to (16,1): {reshaped.shape}\n")

=== Task 1.4: Reshape ===
Original shape: torch.Size([4, 4])
Reshaped to (16,1): torch.Size([16, 1])



# Part 2: Autograd (Automatic Differentiation)

In [19]:
print("=== Part 2: Autograd ===")

x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}, grad_fn: {y.grad_fn}")

z = y * y * 3
z.backward()
print(f"Gradient of z w.r.t x: {x.grad}")

# Explanation:
# z = 3 * (x+2)^2 => dz/dx = 6*(x+2). With x=1 => dz/dx = 18.

=== Part 2: Autograd ===
x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>), grad_fn: <AddBackward0 object at 0x7d7a98238e20>
Gradient of z w.r.t x: tensor([18.])


# Part 3: Building a Simple Model with torch.nn

In [20]:
print("=== Part 3.1: torch.nn.Linear ===")
linear_layer = nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3,5)
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}\nOutput shape: {output.shape}\nOutput:\n{output}\n")

=== Part 3.1: torch.nn.Linear ===
Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
tensor([[ 0.0719, -0.7736],
        [-0.7034, -0.0492],
        [ 0.8157,  0.1238]], grad_fn=<AddmmBackward0>)



In [21]:

print("=== Part 3.2: torch.nn.Embedding ===")
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.LongTensor([1,5,0,8])
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}\nOutput shape: {embeddings.shape}\nEmbeddings:\n{embeddings}\n")

=== Part 3.2: torch.nn.Embedding ===
Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
tensor([[ 0.6321,  0.5991, -0.5192],
        [-0.3467,  0.1080, -0.4335],
        [ 0.3594,  0.2611, -1.8098],
        [-1.6341, -1.2471,  0.7925]], grad_fn=<EmbeddingBackward0>)



In [ ]:
print("=== Part 3.3: Custom Model (nn.Module) ===")
class MyModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

model = MyModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1,2,5,9]])
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}\nOutput:\n{output_data}\n")

=== Part 3.3: Custom Model (nn.Module) ===
Model output shape: torch.Size([1, 4, 2])
Output:
tensor([[[-0.2180,  0.2126],
         [ 0.0234,  0.0381],
         [ 0.1121, -0.0312],
         [-0.0167,  0.1034]]], grad_fn=<ViewBackward0>)

